[theme]
base = "light"
primaryColor = "#E30A17"
backgroundColor = "#F9FAFB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#111827"
font = "sans serif"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false